---
- name: install httpd in RedHat And Apache in debian Server And Start their services
  hosts: webserver
  become: true
  tasks:

    - name: install httpd in redhat serrvert
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: start httpd service
      service:
        name: ht--  # bug intensionally
        state: started
      when: ansible_os_family == "RedHat"
      ignore_errors: yes  

    - name: install apache2 in debian server
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: start apache2 service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "debian"

    - name: copy index file
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html
        mode: 0666

        
