---

- name: install httpd when RedHat server
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"  
  notify: start httpd service

- name: install apache2 in debian server
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2 service

- name: copy index.html file in node
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0666

